<template>
  <div class="flex items-center p-4">
    <div class="flex flex-wrap items-end gap-4">
      <BaseButtonClose
        size="xs"
        rounded="md"
        color="muted"
      />
      <BaseButtonClose
        size="sm"
        rounded="md"
        color="muted"
      />
      <BaseButtonClose
        size="md"
        rounded="md"
        color="muted"
      />
      <BaseButtonClose
        size="lg"
        rounded="md"
        color="muted"
      />
      <BaseButtonClose
        size="xl"
        rounded="md"
        color="muted"
      />
    </div>
  </div>
</template>
