<template>
  <div class="flex items-center p-4">
    <div class="flex flex-wrap items-end gap-3">
      <BaseTag
        rounded="md"
        variant="solid"
        color="default"
      >
        Label
      </BaseTag>
      <BaseTag
        rounded="md"
        variant="solid"
        color="muted"
      >
        Label
      </BaseTag>
      <BaseTag
        rounded="md"
        variant="solid"
        color="primary"
      >
        Label
      </BaseTag>
      <BaseTag
        rounded="md"
        variant="solid"
        color="success"
      >
        Label
      </BaseTag>
      <BaseTag
        rounded="md"
        variant="solid"
        color="info"
      >
        Label
      </BaseTag>
      <BaseTag
        rounded="md"
        variant="solid"
        color="warning"
      >
        Label
      </BaseTag>
      <BaseTag
        rounded="md"
        variant="solid"
        color="danger"
      >
        Label
      </BaseTag>
      <BaseTag
        rounded="md"
        variant="solid"
        color="dark"
      >
        Label
      </BaseTag>
      <BaseTag
        rounded="md"
        variant="solid"
        color="black"
      >
        Label
      </BaseTag>
    </div>
  </div>
</template>
